version: '1.0'
steps:
  clone:
    title: Cloning repository
    type: git-clone
    repo: dglavevski/registry-trigger-sample-app
    revision: '${{CF_BRANCH}}'
    git: github-dg
    stage: clone
  build:
    title: Building Docker image
    type: build
    image_name: dgpipeapp
    working_directory: '${{clone}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile
    stage: build
  test:
    title: Running test
    type: freestyle
    image: 'ubuntu:latest'
    working_directory: '${{clone}}'
    commands:
      - ls
    stage: test
  deploy:
    title: "deploy"
    image: 'ubuntu:latest'
    working_directory: '${{clone}}'
    arguments:
          action: "install"
          kube_context: "${{KUBE_CLUSTER_NAME}}"
          custom_values:
                  - 'buildID=${{CF_BUILD_ID}}'
                  - 'image_pullPolicy=Always'
                  - 'image_tag=2.0.0'
                  - 'replicaCount=3'
stages:
  - clone
  - build
  - test
  - deploy
services: {}
fail_fast: true
